from __future__ import annotations

import argparse
import json
import statistics
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from http.cookiejar import CookieJar
from urllib.parse import urlparse
from urllib.request import HTTPCookieProcessor, Request, build_opener


def request(opener, base_url: str, path: str, method: str = "GET", payload: dict | None = None) -> dict:
    body = None
    headers = {}
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = Request(f"{base_url.rstrip('/')}{path}", data=body, headers=headers, method=method)
    with opener.open(req, timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def assert_local(base_url: str, allow_cloud: bool) -> None:
    host = urlparse(base_url).hostname or ""
    if allow_cloud:
        return
    if host not in {"127.0.0.1", "localhost"}:
        raise SystemExit("Refusing to write dummy data to a non-local CRM. Use --allow-cloud only if you really mean it.")


def dummy_customer(index: int, owners: list[str], statuses: list[str], stages: list[str]) -> dict:
    owner = owners[index % len(owners)] if owners else "Mei"
    won_status = next((status for status in statuses if "成交" in status), statuses[-1] if statuses else "已成交")
    open_status = next((status for status in statuses if "成交" not in status), statuses[0] if statuses else "有兴趣")
    is_won = index % 3 != 0
    amount = 36000 + index * 7000
    collected = amount * (0.35 if index % 2 else 0.75) if is_won else 0
    return {
        "id": f"stress-c{index:02d}",
        "name": f"Stress Dummy {index:02d}",
        "phone": f"019-900 {index:04d}",
        "email": f"stress{index:02d}@example.com",
        "source": "STRESS TEST",
        "status": won_status if is_won else open_status,
        "owner": owner,
        "dealValue": amount if is_won else 0,
        "collectedAmount": collected,
        "programPackage": "Stress Test Package",
        "totalBeforeSst": amount,
        "sstRate": 0,
        "totalAmount": amount,
        "firstPayment": collected,
        "firstPaymentDate": "2026-08-05",
        "monthlyInstallment": 8000 + index * 250,
        "totalTerms": 6,
        "paymentDay": 5 + (index % 20),
        "stage": stages[index % len(stages)] if stages else "MDS AUG",
        "expectedClose": f"2026-08-{min(28, 5 + index):02d}",
        "boosterComment": "Stress test customer.",
        "nextFollowUp": f"2026-08-{min(28, 12 + index):02d}",
        "note": "Generated by stress_test.py",
    }


def add_dummy_data(opener, base_url: str, count: int) -> None:
    state = request(opener, base_url, "/api/state")
    settings = state.get("settings", {})
    owners = sorted({customer.get("owner") for customer in state.get("customers", []) if customer.get("owner")})
    statuses = [status.get("name") for status in settings.get("statuses", []) if status.get("name")]
    stages = settings.get("stages", [])
    activity_type = (settings.get("activityTypes") or ["备注"])[0]

    for index in range(1, count + 1):
        customer = dummy_customer(index, owners, statuses, stages)
        request(opener, base_url, "/api/customers", "POST", customer)
        request(
            opener,
            base_url,
            "/api/activities",
            "POST",
            {
                "customerId": customer["id"],
                "type": activity_type,
                "date": customer["nextFollowUp"],
                "owner": customer["owner"],
                "note": "Stress test follow-up note.",
                "attachments": [],
            },
        )
        if customer["collectedAmount"] > 0:
            request(
                opener,
                base_url,
                "/api/payments",
                "POST",
                {
                    "customerId": customer["id"],
                    "paymentDate": customer["expectedClose"],
                    "termNo": 1,
                    "amount": customer["collectedAmount"],
                    "method": "Stress Test",
                    "slipReceived": "Yes",
                    "remark": "Generated by stress_test.py",
                },
            )


def timed_get(base_url: str, cookies: CookieJar) -> float:
    opener = build_opener(HTTPCookieProcessor(cookies))
    start = time.perf_counter()
    request(opener, base_url, "/api/state")
    return (time.perf_counter() - start) * 1000


def main() -> None:
    parser = argparse.ArgumentParser(description="Local CRM stress test with dummy customer/payment data.")
    parser.add_argument("--base-url", default="http://127.0.0.1:5173")
    parser.add_argument("--username", default="admin")
    parser.add_argument("--password", default="admin123")
    parser.add_argument("--dummy-count", type=int, default=10)
    parser.add_argument("--requests", type=int, default=120)
    parser.add_argument("--concurrency", type=int, default=12)
    parser.add_argument("--allow-cloud", action="store_true")
    args = parser.parse_args()

    assert_local(args.base_url, args.allow_cloud)
    cookies = CookieJar()
    opener = build_opener(HTTPCookieProcessor(cookies))
    request(opener, args.base_url, "/api/login", "POST", {"username": args.username, "password": args.password})
    add_dummy_data(opener, args.base_url, args.dummy_count)

    timings = []
    errors = 0
    with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = [pool.submit(timed_get, args.base_url, cookies) for _ in range(args.requests)]
        for future in as_completed(futures):
            try:
                timings.append(future.result())
            except Exception:
                errors += 1

    timings.sort()
    p95 = timings[int(len(timings) * 0.95) - 1] if timings else 0
    print(f"Dummy customers added: {args.dummy_count}")
    print(f"Requests: {args.requests}, concurrency: {args.concurrency}, errors: {errors}")
    print(f"Average /api/state: {statistics.mean(timings):.1f} ms")
    print(f"P95 /api/state: {p95:.1f} ms")
    print(f"Max /api/state: {max(timings):.1f} ms")


if __name__ == "__main__":
    main()
